AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 20

Resources:
  BlogPosts:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions: 
        - 
          AttributeName: "BlogId"
          AttributeType: "S"
        - 
          AttributeName: "BlogUrl"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "BlogId"
          KeyType: "HASH"
        - 
          AttributeName: "BlogUrl"
          KeyType: "RANGE"
    

  ScrapeBlogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scrape-blog/
      Handler: scrape-blog
      Runtime: go1.x
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Enabled: True